version: 2.1
jobs:
  build-test:
    docker:
      - image: cimg/node:20.9

    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Prepare container
          command: sudo apt update
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      - run: yarn test-unit
      - run: yarn test-integration
      - run: yarn ci-lint

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-test
